# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Swift Playgrounds
        uses: thisIsTheFoxe/swift-playgrounds-action@v1
